ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM* # This works only if one Arduino board is connected

# USE_LIB_PATH = /media/alexandros/TOSHIBA EXT1/Projects/Ball on Beam Project/Arduino Skeatches/libraries
BOARD_TAG = leonardo

include /usr/share/arduino/Arduino.mk 
